<?php

add_action('init', 'custom_fields');

function custom_fields() {

    if(function_exists("register_field_group"))
    {
        register_field_group(array (
            'id' => 'acf_event',
            'title' => 'Event',
            'fields' => array (
                array (
                    'key' => 'field_533dbf4a034c0',
                    'label' => 'Type of event',
                    'name' => 'event_type',
                    'type' => 'select',
                    'required' => 1,
                    'choices' => array (
                        'bos' => 'Business of Software US',
                        'boseu' => 'Business of Software Europe',
                        'bosuk' => 'Business of Software UK',
                        'iot' => 'Internet of Things',
                        'mim' => 'Making it Mobile',
                    ),
                    'default_value' => '',
                    'allow_null' => 0,
                    'multiple' => 0,
                ),
                array (
                    'key' => 'field_5310a04d1c999',
                    'label' => 'Event start date',
                    'name' => 'event_start',
                    'type' => 'date_picker',
                    'instructions' => 'Required to move event into recent events list',
                    'required' => 1,
                    'date_format' => 'yymmdd',
                    'display_format' => 'dd/mm/yy',
                    'first_day' => 1,
                ),
                array (
                    'key' => 'field_5310a04d1caaa',
                    'label' => 'Event end date',
                    'name' => 'event_end',
                    'type' => 'date_picker',
                    'instructions' => '',
                    'required' => 1,
                    'date_format' => 'yymmdd',
                    'display_format' => 'dd/mm/yy',
                    'first_day' => 1,
                ),
                array (
                    'key' => 'field_533dc0575e975',
                    'label' => 'Event display date',
                    'name' => 'event_date',
                    'type' => 'text',
                    'instructions' => 'e.g. 1st April 1 2014 -or- 25-26th June 2014',
                    'required' => 1,
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'formatting' => 'none',
                    'maxlength' => 30,
                ),
                array (
                    'key' => 'field_533f37af32b24',
                    'label' => 'Alert',
                    'name' => 'event_alert',
                    'type' => 'text',
                    'instructions' => 'Short alert shown in page header area (maximum of 40 characters)',
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'formatting' => 'none',
                    'maxlength' => 40,
                ),
                array (
                    'key' => 'field_533f372747991',
                    'label' => 'Registration URL',
                    'name' => 'event_register_url',
                    'type' => 'text',
                    'instructions' => 'URL of EventBrite registration page',
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'formatting' => 'none',
                    'maxlength' => '',
                ),
                array (
                    'key' => 'field_53425f83f811f',
                    'label' => 'Programmes',
                    'name' => 'event_programmes',
                    'type' => 'relationship',
                    'return_format' => 'id',
                    'post_type' => array (
                        0 => 'programme',
                    ),
                    'taxonomy' => array (
                        0 => 'all',
                    ),
                    'filters' => array (
                        0 => 'search',
                    ),
                    'result_elements' => array (
                        0 => 'post_type',
                        1 => 'post_title',
                    ),
                    'max' => '',
                ),
                array (
                    'key' => 'field_533dc116116e3',
                    'label' => 'Venue',
                    'name' => 'event_venue',
                    'type' => 'relationship',
                    'return_format' => 'id',
                    'post_type' => array (
                        0 => 'venue',
                    ),
                    'taxonomy' => array (
                        0 => 'all',
                    ),
                    'filters' => array (
                        0 => 'search',
                    ),
                    'result_elements' => array (
                        0 => 'post_type',
                        1 => 'post_title',
                    ),
                    'max' => '',
                ),
                array (
                    'key' => 'field_533eb16183b71',
                    'label' => 'Main menu',
                    'name' => 'event_menu',
                    'type' => 'relationship',
                    'return_format' => 'id',
                    'post_type' => array (
                        0 => 'page',
                    ),
                    'taxonomy' => array (
                        0 => 'all',
                    ),
                    'filters' => array (
                        0 => 'search',
                    ),
                    'result_elements' => array (
                        0 => 'post_type',
                        1 => 'post_title',
                    ),
                    'max' => '',
                ),
                array (
                    'key' => 'field_534559aa757ca',
                    'label' => 'Gold sponsors',
                    'name' => 'event_gold_sponsors',
                    'type' => 'relationship',
                    'return_format' => 'id',
                    'post_type' => array (
                        0 => 'company',
                    ),
                    'taxonomy' => array (
                        0 => 'all',
                    ),
                    'filters' => array (
                        0 => 'search',
                    ),
                    'result_elements' => array (
                        0 => 'post_type',
                        1 => 'post_title',
                    ),
                    'max' => '',
                ),
                array (
                    'key' => 'field_534559d5ef57a',
                    'label' => 'Silver sponsors',
                    'name' => 'event_silver_sponsors',
                    'type' => 'relationship',
                    'return_format' => 'id',
                    'post_type' => array (
                        0 => 'company',
                    ),
                    'taxonomy' => array (
                        0 => 'all',
                    ),
                    'filters' => array (
                        0 => 'search',
                    ),
                    'result_elements' => array (
                        0 => 'post_type',
                        1 => 'post_title',
                    ),
                    'max' => '',
                ),
                array (
                    'key' => 'field_534559f26d178',
                    'label' => 'Bronze sponsors',
                    'name' => 'event_bronze_sponsors',
                    'type' => 'relationship',
                    'return_format' => 'id',
                    'post_type' => array (
                        0 => 'company',
                    ),
                    'taxonomy' => array (
                        0 => 'all',
                    ),
                    'filters' => array (
                        0 => 'search',
                    ),
                    'result_elements' => array (
                        0 => 'post_type',
                        1 => 'post_title',
                    ),
                    'max' => '',
                ),
                array (
                    'key' => 'field_53455a5560a0b',
                    'label' => 'Media sponsors',
                    'name' => 'event_media_sponsors',
                    'type' => 'relationship',
                    'return_format' => 'id',
                    'post_type' => array (
                        0 => 'company',
                    ),
                    'taxonomy' => array (
                        0 => 'all',
                    ),
                    'filters' => array (
                        0 => 'search',
                    ),
                    'result_elements' => array (
                        0 => 'post_type',
                        1 => 'post_title',
                    ),
                    'max' => '',
                ),
            ),
            'location' => array (
                array (
                    array (
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'event',
                        'order_no' => 0,
                        'group_no' => 0,
                    ),
                ),
            ),
            'options' => array (
                'position' => 'normal',
                'layout' => 'no_box',
                'hide_on_screen' => array (
                    0 => 'permalink',
                    1 => 'the_content',
                    2 => 'excerpt',
                    3 => 'custom_fields',
                    4 => 'discussion',
                    5 => 'comments',
                    6 => 'slug',
                    7 => 'author',
                    8 => 'format',
                    9 => 'featured_image',
                    10 => 'categories',
                    11 => 'tags',
                    12 => 'send-trackbacks',
                ),
            ),
            'menu_order' => 0,
        ));

        register_field_group(array (
            'id' => 'acf_home',
            'title' => 'Home',
            'fields' => array (
                          array (
                    'key' => 'field_53431ed122ae8',
                    'label' => 'Hero box',
                    'name' => 'home_hero',
                    'type' => 'wysiwyg',
                    'instructions' => 'Your hero overlay must contain no more than 400 characters.
        The first line should be an H2',
                    'required' => 1,
                    'default_value' => '',
                    'toolbar' => 'full',
                    'media_upload' => 'no',
                ),
                array (
                    'key' => 'field_534323210504f',
                    'label' => 'Title aside',
                    'name' => 'home_aside',
                    'type' => 'wysiwyg',
                    'instructions' => 'Block of text displayed to the right of Updates button (240 characters or less).
        First line should be an H3',
                    'default_value' => '',
                    'toolbar' => 'full',
                    'media_upload' => 'no',
                ),
                array (
                    'key' => 'field_5343196990603',
                    'label' => 'Pitch',
                    'name' => 'home_pitch',
                    'type' => 'wysiwyg',
                    'instructions' => 'Appears between featured speakers and testimonials. First line should be an H2',
                    'required' => 1,
                    'default_value' => '',
                    'toolbar' => 'full',
                    'media_upload' => 'no',
                )
            ),
            'location' => array (
                array (
                    array (
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'page-templates/home.php',
                        'order_no' => 0,
                        'group_no' => 0,
                    ),
                ),
            ),
            'options' => array (
                'position' => 'normal',
                'layout' => 'no_box',
                'hide_on_screen' => array (
                    0 => 'the_content',
                    1 => 'excerpt',
                    2 => 'custom_fields',
                    3 => 'discussion',
                    4 => 'comments',
                    5 => 'revisions',
                    6 => 'slug',
                    7 => 'author',
                    8 => 'format',
                    9 => 'featured_image',
                    10 => 'categories',
                    11 => 'tags',
                    12 => 'send-trackbacks',
                ),
            ),
            'menu_order' => 0,
        ));

        register_field_group(array (
            'id' => 'acf_programme',
            'title' => 'Programme',
            'fields' => array (
                array (
                    'key' => 'field_534259e3a3780',
                    'label' => 'Date',
                    'name' => 'programme_date',
                    'type' => 'date_picker',
                    'required' => 0,
                    'date_format' => 'yymmdd',
                    'display_format' => 'dd/mm/yy',
                    'first_day' => 1,
                ),
                array (
                    'key' => 'field_53425a0ed842f',
                    'label' => 'Type',
                    'name' => 'programme_type',
                    'type' => 'select',
                    'required' => 1,
                    'choices' => array (
                        'pre' => 'Pre-conference',
                        'main' => 'Sessions',
                        'workshop' => 'Workshops',
                        'post' => 'Post-conference',
                    ),
                    'default_value' => 'main',
                    'allow_null' => 0,
                    'multiple' => 0,
                ),
                array (
                    'key' => 'field_53425ef2bac5f',
                    'label' => 'Sessions',
                    'name' => 'programme_sessions',
                    'type' => 'relationship',
                    'required' => 1,
                    'return_format' => 'id',
                    'post_type' => array (
                        0 => 'session',
                    ),
                    'taxonomy' => array (
                        0 => 'all',
                    ),
                    'filters' => array (
                        0 => 'search',
                    ),
                    'result_elements' => array (
                        0 => 'post_type',
                        1 => 'post_title',
                    ),
                    'max' => '',
                ),
            ),
            'location' => array (
                array (
                    array (
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'programme',
                        'order_no' => 0,
                        'group_no' => 0,
                    ),
                ),
            ),
            'options' => array (
                'position' => 'normal',
                'layout' => 'no_box',
                'hide_on_screen' => array (
                    0 => 'permalink',
                    1 => 'the_content',
                    2 => 'excerpt',
                    3 => 'custom_fields',
                    4 => 'discussion',
                    5 => 'comments',
                    6 => 'revisions',
                    7 => 'slug',
                    8 => 'author',
                    9 => 'format',
                    10 => 'featured_image',
                    11 => 'categories',
                    12 => 'tags',
                    13 => 'send-trackbacks',
                ),
            ),
            'menu_order' => 0,
        ));
        
        register_field_group(array (
            'id' => 'acf_session',
            'title' => 'Session',
            'fields' => array (
                array (
                    'key' => 'field_5340676453094',
                    'label' => 'Type',
                    'name' => 'session_type',
                    'type' => 'select',
                    'instructions' => 'What type of session is this?',
                    'required' => 1,
                    'choices' => array (
                        'registration' => 'Registration',
                        'reception' => 'Reception',
                        'breakfast' => 'Breakfast',
                        'welcome' => 'Welcome',
                        'talk' => 'Talk',
                        'lightning' => 'Lightning talk',
                        'pitch' => 'Company presentation',
                        'panel' => 'Panel discussion',
                        'break' => 'Break',
                        'lunch' => 'Lunch',
                        'close' => 'Close of day',
                        'party' => 'After party',
                        'retire' => 'Bedtime',
                        'photowalk' => 'Photo walk',
                        'workshop' => 'Workshop',
                        'sponsor' => 'Sponsor presentation',
                    ),
                    'default_value' => 'talk',
                    'allow_null' => 0,
                    'multiple' => 0,
                ),
                array (
                    'key' => 'field_53406b83da93d',
                    'label' => 'Description',
                    'name' => 'session_description',
                    'type' => 'wysiwyg',
                    'instructions' => 'You need to provide a brief excerpt (200 characters or less) and a longer description of the session.',
                    'required' => 1,
                    'default_value' => '',
                    'toolbar' => 'full',
                    'media_upload' => 'no',
                ),
                array (
                    'key' => 'field_534062c656829',
                    'label' => 'Start time',
                    'name' => 'session_start',
                    'type' => 'text',
                    'instructions' => 'Session start time e.g 08:30',
                    'required' => 0,
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'formatting' => 'none',
                    'maxlength' => '',
                ),
                array (
                    'key' => 'field_53406b5da157f',
                    'label' => 'Speakers',
                    'name' => 'session_speakers',
                    'type' => 'relationship',
                    'instructions' => 'Select any speakers involved in the session',
                    'return_format' => 'id',
                    'post_type' => array (
                        0 => 'speaker',
                    ),
                    'taxonomy' => array (
                        0 => 'all',
                    ),
                    'filters' => array (
                        0 => 'search',
                    ),
                    'result_elements' => array (
                        0 => 'post_type',
                        1 => 'post_title',
                    ),
                    'max' => 0,
                ),
                array (
                    'key' => 'field_5342b5feda0a4',
                    'label' => 'Moderator',
                    'name' => 'session_moderators',
                    'type' => 'relationship',
                    'instructions' => 'You only need to add a moderator for interviews, panel discussions or workshops',
                    'return_format' => 'id',
                    'post_type' => array (
                        0 => 'speaker',
                    ),
                    'taxonomy' => array (
                        0 => 'all',
                    ),
                    'filters' => array (
                        0 => 'search',
                    ),
                    'result_elements' => array (
                        0 => 'post_type',
                        1 => 'post_title',
                    ),
                    'max' => '',
                ),
                array (
                    'key' => 'field_534480acbeec2',
                    'label' => 'Companies',
                    'name' => 'session_companies',
                    'type' => 'relationship',
                    'instructions' => 'You only need to add companies for company presentation sessions',
                    'return_format' => 'id',
                    'post_type' => array (
                        0 => 'company',
                    ),
                    'taxonomy' => array (
                        0 => 'all',
                    ),
                    'filters' => array (
                        0 => 'search',
                    ),
                    'result_elements' => array (
                        0 => 'post_type',
                        1 => 'post_title',
                    ),
                    'max' => '',
                ),
                array (
                    'key' => 'field_557862c656830',
                    'label' => 'Registration URL',
                    'name' => 'session_reg_url',
                    'type' => 'text',
                    'instructions' => 'URL\'s must start with http://',
                    'required' => 0,
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'formatting' => 'none',
                    'maxlength' => '',
                ),
            ),
            'location' => array (
                array (
                    array (
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'session',
                        'order_no' => 0,
                        'group_no' => 0,
                    ),
                ),
            ),
            'options' => array (
                'position' => 'normal',
                'layout' => 'no_box',
                'hide_on_screen' => array (
                    0 => 'the_content',
                    1 => 'excerpt',
                    2 => 'custom_fields',
                    3 => 'discussion',
                    4 => 'comments',
                    5 => 'revisions',
                    6 => 'slug',
                    7 => 'author',
                    8 => 'format',
                    9 => 'featured_image',
                    10 => 'categories',
                    11 => 'tags',
                    12 => 'send-trackbacks',
                ),
            ),
            'menu_order' => 0,
        ));

        register_field_group(array (
            'id' => 'acf_speaker',
            'title' => 'Speaker',
            'fields' => array (
                array (
                    'key' => 'field_533dd37588b9e',
                    'label' => 'Featured',
                    'name' => 'speaker_featured',
                    'type' => 'true_false',
                    'message' => 'Feature at top of speakers list',
                    'default_value' => 0,
                ),
                 array (
                    'key' => 'field_533dd37588a5a',
                    'label' => 'Cloaked',
                    'name' => 'speaker_lightning',
                    'type' => 'true_false',
                    'message' => 'Don\'t show in speakers list',
                    'default_value' => 0,
                ),
                array (
                    'key' => 'field_533dca02b1c91',
                    'label' => 'Photo',
                    'name' => 'speaker_image',
                    'type' => 'image',
                    'instructions' => 'Uploaded images must be at least 256 x 256 pixels',
                    'required' => 1,
                    'save_format' => 'id',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                ),
                array (
                    'key' => 'field_533dca862ba4a',
                    'label' => 'Job title',
                    'name' => 'speaker_title',
                    'type' => 'text',
                    'instructions' => 'e.g. CEO or Investor',
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'formatting' => 'none',
                    'maxlength' => '',
                ),
                array (
                    'key' => 'field_533dcabc9fe11',
                    'label' => 'Organisation',
                    'name' => 'speaker_org',
                    'type' => 'text',
                    'instructions' => 'e.g. Apple Computer',
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'formatting' => 'none',
                    'maxlength' => '',
                ),
                array (
                    'key' => 'field_533dcafd8490e',
                    'label' => 'Biography',
                    'name' => 'speaker_bio',
                    'type' => 'wysiwyg',
                    'instructions' => 'Speaker bio excerpts must be less than 140 characters',
                    'required' => 1,
                    'default_value' => '',
                    'toolbar' => 'full',
                    'media_upload' => 'no',
                ),
            ),
            'location' => array (
                array (
                    array (
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'speaker',
                        'order_no' => 0,
                        'group_no' => 0,
                    ),
                ),
            ),
            'options' => array (
                'position' => 'normal',
                'layout' => 'no_box',
                'hide_on_screen' => array (
                    0 => 'permalink',
                    1 => 'the_content',
                    2 => 'excerpt',
                    3 => 'custom_fields',
                    4 => 'discussion',
                    5 => 'comments',
                    6 => 'revisions',
                    7 => 'slug',
                    8 => 'author',
                    9 => 'format',
                    10 => 'categories',
                    11 => 'tags',
                    12 => 'send-trackbacks',
                ),
            ),
            'menu_order' => 0,
        ));

        register_field_group(array (
            'id' => 'acf_testimonial',
            'title' => 'Testimonial',
            'fields' => array (
                array (
                    'key' => 'field_5343d4fa9c671',
                    'label' => 'Testimonial',
                    'name' => 'testimonial_text',
                    'type' => 'textarea',
                    'instructions' => 'Testimonials should be no more than 150 characters long',
                    'required' => 1,
                    'default_value' => '',
                    'placeholder' => '',
                    'maxlength' => 150,
                    'rows' => '',
                    'formatting' => 'none',
                ),
                array (
                    'key' => 'field_5343d576456a5',
                    'label' => 'Feature testimonial',
                    'name' => 'testimonial_featured',
                    'type' => 'true_false',
                    'message' => 'Feature testimonial on home page',
                    'default_value' => 0,
                ),
            ),
            'location' => array (
                array (
                    array (
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'testimonial',
                        'order_no' => 0,
                        'group_no' => 0,
                    ),
                ),
            ),
            'options' => array (
                'position' => 'normal',
                'layout' => 'no_box',
                'hide_on_screen' => array (
                    0 => 'permalink',
                    1 => 'the_content',
                    2 => 'excerpt',
                    3 => 'custom_fields',
                    4 => 'discussion',
                    5 => 'comments',
                    6 => 'revisions',
                    7 => 'slug',
                    8 => 'author',
                    9 => 'format',
                    10 => 'featured_image',
                    11 => 'categories',
                    12 => 'tags',
                    13 => 'send-trackbacks',
                ),
            ),
            'menu_order' => 0,
        ));

        register_field_group(array (
            'id' => 'acf_venue',
            'title' => 'Venue',
            'fields' => array (
                array (
                    'key' => 'field_533dc423d7006',
                    'label' => 'City',
                    'name' => 'venue_city',
                    'type' => 'text',
                    'instructions' => 'e.g Cambridge -or- Boston MA',
                    'required' => 1,
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'formatting' => 'none',
                    'maxlength' => '',
                ),
                array (
                    'key' => 'field_533dc470d7008',
                    'label' => 'Description',
                    'name' => 'venue_description',
                    'type' => 'wysiwyg',
                    'instructions' => 'Remember to include the venue address and any relevant travel information',
                    'required' => 1,
                    'default_value' => '',
                    'toolbar' => 'full',
                    'media_upload' => 'no',
                ),
                array (
                    'key' => 'field_533dc4c36544d',
                    'label' => 'Map',
                    'name' => 'venue_map',
                    'type' => 'textarea',
                    'instructions' => 'Paste the embedded Google map code for the venue',
                    'required' => 1,
                    'default_value' => '',
                    'placeholder' => '',
                    'maxlength' => '',
                    'rows' => '',
                    'formatting' => 'html',
                ),
            ),
            'location' => array (
                array (
                    array (
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'venue',
                        'order_no' => 0,
                        'group_no' => 0,
                    ),
                ),
            ),
            'options' => array (
                'position' => 'normal',
                'layout' => 'no_box',
                'hide_on_screen' => array (
                    0 => 'permalink',
                    1 => 'the_content',
                    2 => 'excerpt',
                    3 => 'custom_fields',
                    4 => 'discussion',
                    5 => 'comments',
                    6 => 'revisions',
                    7 => 'slug',
                    8 => 'author',
                    9 => 'format',
                    10 => 'featured_image',
                    11 => 'categories',
                    12 => 'tags',
                    13 => 'send-trackbacks',
                ),
            ),
            'menu_order' => 0,
        ));

        register_field_group(array (
            'id' => 'acf_company',
            'title' => 'Company',
            'fields' => array (
                array (
                    'key' => 'field_53443f45e1df1',
                    'label' => 'Logo',
                    'name' => 'company_image',
                    'type' => 'image',
                    'instructions' => 'Company logos must be 212 x 114 pixels',
                    'save_format' => 'id',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                ),
                array (
                    'key' => 'field_53443f8ececf1',
                    'label' => 'Profile',
                    'name' => 'company_profile',
                    'type' => 'wysiwyg',
                    'instructions' => 'Profile excerpts must be no more than 140 characters',
                    'required' => 1,
                    'default_value' => '',
                    'toolbar' => 'full',
                    'media_upload' => 'no',
                ),
                array (
                    'key' => 'field_53443ff35ae70',
                    'label' => 'URL',
                    'name' => 'company_url',
                    'type' => 'text',
                    'instructions' => 'URL\'s must start with http://',
                    'required' => 1,
                    'default_value' => 'http://',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'formatting' => 'none',
                    'maxlength' => '',
                ),
            ),
            'location' => array (
                array (
                    array (
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'company',
                        'order_no' => 0,
                        'group_no' => 0,
                    ),
                ),
            ),
            'options' => array (
                'position' => 'normal',
                'layout' => 'no_box',
                'hide_on_screen' => array (
                    0 => 'permalink',
                    1 => 'the_content',
                    2 => 'excerpt',
                    3 => 'custom_fields',
                    4 => 'discussion',
                    5 => 'comments',
                    6 => 'revisions',
                    7 => 'slug',
                    8 => 'author',
                    9 => 'format',
                    10 => 'categories',
                    11 => 'tags',
                    12 => 'send-trackbacks',
                ),
            ),
            'menu_order' => 0,
        ));

        register_field_group(array (
            'id' => 'acf_exhibition',
            'title' => 'Exhibition',
            'fields' => array (
                array (
                    'key' => 'field_53444895a2454',
                    'label' => 'Subtitle',
                    'name' => 'page_subtitle',
                    'type' => 'text',
                    'instructions' => 'Subtitles should be no more than 140 characters',
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'formatting' => 'none',
                    'maxlength' => '',
                ),
                array (
                    'key' => 'field_53444875a2453',
                    'label' => 'Aside',
                    'name' => 'page_aside',
                    'type' => 'wysiwyg',
                    'instructions' => 'Block of text displayed to the right of the page title (240 characters or less)',
                    'default_value' => '',
                    'toolbar' => 'full',
                    'media_upload' => 'no',
                ),
                array (
                    'key' => 'field_534444a3f6039',
                    'label' => 'Companies',
                    'name' => 'exhibition_companies',
                    'type' => 'relationship',
                    'return_format' => 'id',
                    'post_type' => array (
                        0 => 'company',
                    ),
                    'taxonomy' => array (
                        0 => 'all',
                    ),
                    'filters' => array (
                        0 => 'search',
                    ),
                    'result_elements' => array (
                        0 => 'post_type',
                        1 => 'post_title',
                    ),
                    'max' => '',
                ),
            ),
            'location' => array (
                array (
                    array (
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'page-templates/exhibition.php',
                        'order_no' => 0,
                        'group_no' => 0,
                    ),
                ),
            ),
            'options' => array (
                'position' => 'normal',
                'layout' => 'no_box',
                'hide_on_screen' => array (
                    0 => 'permalink',
                    1 => 'the_content',
                    2 => 'excerpt',
                    3 => 'custom_fields',
                    4 => 'discussion',
                    5 => 'comments',
                    6 => 'revisions',
                    7 => 'slug',
                    8 => 'author',
                    9 => 'format',
                    10 => 'featured_image',
                    11 => 'categories',
                    12 => 'tags',
                    13 => 'send-trackbacks',
                ),
            ),
            'menu_order' => 0,
        ));

        register_field_group(array (
            'id' => 'acf_talks',
            'title' => 'Talks',
            'fields' => array (
                array (
                    'key' => 'field_5355ca61bea62',
                    'label' => 'Recommended talk',
                    'name' => 'talk_featured',
                    'type' => 'true_false',
                    'message' => 'Display this talk at top of the talks page',
                    'default_value' => 0,
                ),
                array (
                    'key' => 'field_530e375710d66',
                    'label' => 'Talk image (256 x 256 px)',
                    'name' => 'talk_image',
                    'type' => 'image',
                    'required' => 1,
                    'save_format' => 'id',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                ),
                array (
                    'key' => 'field_530e378910d67',
                    'label' => 'Description',
                    'name' => 'talk_description',
                    'type' => 'wysiwyg',
                    'required' => 1,
                    'default_value' => '',
                    'toolbar' => 'full',
                    'media_upload' => 'no',
                ),
                array (
                    'key' => 'field_5304c6900c154',
                    'label' => 'Speaker',
                    'name' => 'talk_speaker',
                    'type' => 'relationship',
                    'return_format' => 'id',
                    'post_type' => array (
                        0 => 'speaker',
                    ),
                    'taxonomy' => array (
                        0 => 'all',
                    ),
                    'filters' => array (
                        0 => 'search',
                    ),
                    'result_elements' => array (
                        0 => 'post_type',
                        1 => 'post_title',
                    ),
                    'max' => '',
                    'required' => 1,
                ),
                array (
                    'key' => 'field_5304c93044b12',
                    'label' => 'Event (max 1 event)',
                    'name' => 'talk_event',
                    'type' => 'relationship',
                    'return_format' => 'id',
                    'post_type' => array (
                        0 => 'event',
                    ),
                    'taxonomy' => array (
                        0 => 'all',
                    ),
                    'filters' => array (
                        0 => 'search',
                    ),
                    'result_elements' => array (
                        0 => 'post_title',
                    ),
                    'max' => 1,
                ),
            ),
            'location' => array (
                array (
                    array (
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'talk',
                        'order_no' => 0,
                        'group_no' => 0,
                    ),
                ),
            ),
            'options' => array (
                'position' => 'acf_after_title',
                'layout' => 'default',
                'hide_on_screen' => array (
                    0 => 'permalink',
                    1 => 'the_content',
                    2 => 'excerpt',
                    3 => 'custom_fields',
                    4 => 'discussion',
                    5 => 'comments',
                    6 => 'revisions',
                    7 => 'slug',
                    8 => 'author',
                    9 => 'format',
                    10 => 'featured_image',
                    11 => 'tags',
                    12 => 'send-trackbacks',
                    13 => 'categories',
                ),
            ),
            'menu_order' => 0,
        ));

    }
}

?>